#!/bin/sh

# LDC/GDC don't include rdmd, so allow user to specify path to it in $RDMD.
# Otherwise, use "rdmd".
#
# For travis, if "rdmd" doesn't work (ie, LDC/GDC is being tested), then use
# the copy of rdmd that was downloaded by the 'travis-install-deps.sh' script.
if [ -z "$RDMD" ]; then
	RDMD=rdmd
	command -v $RDMD >/dev/null 2>&1 || RDMD=local-dmd/dmd2/${TRAVIS_OS_NAME}/bin64/rdmd
fi

if [ -z "$DMD" ]; then
	DMD=dmd
fi

echo Using:
echo "  RDMD=$RDMD"
echo "  DMD=$DMD"

echo Compiling Phobos-socket tests...
$RDMD --compiler=$DMD --build-only -g -unittest -debug=MYSQL_INTEGRATION_TESTS -ofbin/mysqln-tests-phobos -Isource source/mysql/connection.d && echo Running Phobos-socket tests... && bin/mysqln-tests-phobos
